### ISSUE TITLE
"What is Ruffle" logo is stretched horizontally when 400<x<1000

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle-rs.github.io#11]
What is Ruffle logo is stretched horizontally when width is more than 400px and less than 1000px.

![image](https://user-images.githubusercontent.com/51363864/100499441-c0e8e300-31bd-11eb-9132-f932a9b0397b.png) (only extension I have in incognito is Google Images Restored btw)

**Comment by Herschel** [comment]
@Thoorium Want to take a look at this?

**Comment by Poopooracoocoo** [comment]
![image](https://user-images.githubusercontent.com/51363864/100514587-2642d100-31ca-11eb-9b51-4d4462fb99e0.png)
:P How's this for a fix? Should I open a PR?

**Comment by Thoorium** [comment]
I'll take a look. Thank you for the report!
