### ISSUE TITLE
Improve blog design

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle-rs.github.io#127]
The [blog](https://ruffle.rs/blog/2023/03/12/progress-report.html) could use some love from someone with design/SASS/jekyll skills.

Just some issues that jump out to my unsophisticated programmer eye:
- Margins/padding are inconsistent:
  - Line height feels very crowded.
  - Notice that SolarMax 2 video has no proper padding from the line above it.
  - The headings do not have enough padding from the preceding paragraph.
  - The blog title header has a smaller font size than the mid-post headers.
  - Videos and images should possibly be centered and also have a caption.
  - The top nav bar should have a solid background, as the page content will scroll behind it.

**Comment by Thoorium** [comment]
Hey there! I could look into this in the upcoming week(s) when I'll be less busy, if there's no rush requirements to this task. I would address the most glaring issues first then we can style it up to look amazing :)

**Comment by Thoorium** [comment]
I did a first pass and I'm going over some feedback with DB. I'll merge when we decide its good enough so you can get started with the blog :)

**Comment by danielhjacobs** [comment]
Closing as #137, #138, and #146 have put the blog's design in a much nicer place. Feel free to reopen the issue with further suggestions though.
