### ISSUE TITLE
RSS feed link is incorrect

### ISSUE THREAD

**Issue by dbz2k** [ruffle-rs/ruffle-rs.github.io#128]
I was wondering if you could implement RSS feed for the blog.

**Comment by n0samu** [comment]
There are quite a few improvements that need to be made to the blog functionality and design right now (see #127). This would be one of them, I think!

**Comment by robinheidrich** [comment]
There's a RSS feed already at https://ruffle.rs/feed

**Comment by TobiX** [comment]
It seems the canonical URLs in the blog and in the feed itself point to https://github.com/feed.xml, which breaks the subscribe feature of most feed readers.

**Comment by cdman** [comment]
+1, would be nice if the "link" tag was populated with the correct url (https://ruffle.rs/feed). https://github.com/jekyll/jekyll-feed says that it should also populate it, but who knows. Maybe the feed path needs to be specified? https://github.com/jekyll/jekyll-feed#already-have-a-feed-path

**Comment by n0samu** [comment]
Fixed by #145!

**Comment by cdman** [comment]
Thank you, works great!
