### ISSUE TITLE
April 2023 progress report

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle-rs.github.io#132]
We can use an issue to keep track of things to talk about in progress reports. Feel free to post about interesting developments and newly functioning content we may want to mention.

 * BitmapData optimizations by @Dinnerbone
 * Shape memory leak improvements by @Dinnerbone
 * Continued Stage3D work by @Aaron1011 (MSAA)
 * VVVVVV playable
 * Save data manager by @danielhjacobs 

New contributors:
 * @AllinolCP
 * @emgfc
 * @evilpie
 * @onkrot
 * @yoganlava

New implemented APIs: (TODO add more)
 * AVM1:
   * `XML.getBytesLoaded()`
   * `XML.getBytesTotal()`
 * AVM2:
   * `decodeURI`
   * `decodeURIComponent`
   * `Transform.pixelBounds`

**Comment by n0samu** [comment]
And the new save data manager by @danielhjacobs! 😃

**Comment by Herschel** [comment]
Yep, I think monthly works with the current rate of activity. Can change to bi-monthly as things slow down.

**Comment by n0samu** [comment]
Done in #154
