### ISSUE TITLE
Ruffle logo on the front-page isn't displayed correctly on Safari

### ISSUE THREAD

**Issue by Korne127** [ruffle-rs/ruffle-rs.github.io#143]
The Ruffle logo (SWF) that is embedded on the front-page [(https://ruffle.rs](https://ruffle.rs)) isn't displayed correctly on Safari on macOS.
On Firefox, the website looks like this (which is probably how it's intended):
<img width="1552" alt="Ruffle-Logo Firefox" src="https://user-images.githubusercontent.com/33464213/231517945-926c2a19-e177-4bad-b1c1-9858c551f4b6.png">

However, on Safari, the website looks like this:
<img width="1552" alt="Ruffle-Logo Safari" src="https://user-images.githubusercontent.com/33464213/231518121-f89205be-beee-43e0-a942-6805f9d3fde3.png">

The logo seems to be way too small, and as a result there is a huge amount of blank space. The animation itself works correctly though.

Additionally, when loading the website in Safari, it looks like this:

https://user-images.githubusercontent.com/33464213/231519998-5ec55b9d-f1cf-4224-9fbf-a8204d7b8c4e.mov

As you see, there is a text (Backup all saves (download all sols)) with a horizontal line for a short amount of time before the logo is loaded and the animation is starting.

**Comment by danielhjacobs** [comment]
What version of Safari are you using? The dialog element for the save managrr not working properly points to a version before 15.4: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

**Comment by Korne127** [comment]
That's probably the issue. I'm still on macOS 11 (Big Sur) and since the Safari versions are tied to the macOS versions, I'm using Safari 14.
However, if the front-page depends on an element that doesn't work in some rather new browser versions to be rendered correctly, I'd suggest to have a fallback to display it correctly for browsers that don't support it (if it couldn't work with the SWF file, maybe a static logo) or at least a note that the website isn't displayed correctly in the current browser.

**Comment by danielhjacobs** [comment]
The Ruffle logo being the wrong size is because the Ruffle home page uses [aspect-ratio](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio#browser_compatibility).

**Comment by Korne127** [comment]
Ah, I understand. Well, I am not really an HTML/CSS expert, but could be `padding-top: 56.25%; /* 16:9 aspect ratio */` used instead of (or additionally to??) the aspect-ratio tag to achieve a greater compatibility?

**Comment by danielhjacobs** [comment]
I tried that out a bit, but it doesn't seem to keep the size responsive.
