### ISSUE TITLE
Can't select any SWF file on Safari on iPad OS 17 (iOS bug?)

### ISSUE THREAD

**Issue by orazioedoardo** [ruffle-rs/ruffle-rs.github.io#176]
Clicking "Select File" opens up the system file select sheet, as expected. However all SWF files are greyed out and thus not selectable. Through some empirical test, it looks like to me that Safari is not allowing input elements `type="file"` with attribute `accept=".swf,.spl"`. I've also tried `application/x-shockwave-flash` and it’s not accepted either. However if I select "Request mobile site" in the Safari UI, then I can select any file, not just SWF and SPL, which is exactly what happens on iOS, where mobile version is the default. Can you confirm?

**Comment by danielhjacobs** [comment]
What's your User Agent? Unfortunately, even though it's bad practice, the presence or lack of the "accept" is determined by user-agent sniffing. See https://github.com/ruffle-rs/ruffle/pull/5025

**Comment by danielhjacobs** [comment]
"With iPadOS, Apple has started to position the iPad as a productivity device much like a traditional laptop or desktop. As part of that change, the Safari web browser on iPadOS defaults to sending a User-Agent string that appears to be from a macOS device instead of an iOS or an iPadOS device.": https://help.duo.com/s/article/5187?language=en_US

**Comment by danielhjacobs** [comment]
I think we need this check: https://stackoverflow.com/a/62979491

**Comment by orazioedoardo** [comment]
> What's your User Agent?

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.1 Safari/605.1.15`

**Comment by danielhjacobs** [comment]
What about `navigator.platform` and `navigator.standalone`?

**Comment by orazioedoardo** [comment]
`MacIntel` and `false`.

**Comment by danielhjacobs** [comment]
Ok, this should be fixed once I fix the TS errors on https://github.com/ruffle-rs/ruffle/pull/14017 and it gets merged.

**Comment by orazioedoardo** [comment]
> this should be fixed

Confirmed.
