### ISSUE TITLE
Hero logo improvement ideas

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle-rs.github.io#209]
Just jotting down some ideas for ways the main Ruffle logo animation on the front page could be improved IMHO.

I think if either the Ruffle application (.wasm from CDN) or the logo SWF took too long, or completely failed, to download; or if there was a panic, the canvas could be replaced entirely with an animated GIF or (perhaps better) a static image of the logo.

And as for the logo SWF itself, after all the letters were completely consumed by a couple clicks, perhaps the float-in animation could start again after a short while, not just on the next click, so it doesn't stay empty indefinitely.

**Comment by danielhjacobs** [comment]
#232 addresses paragraph 2. Paragraph 3 requires editing the SWF itself, which I'm not comfortable doing.
