### ISSUE TITLE
The main page is _just a little bit_ too tall, maybe?

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle-rs.github.io#237]
This is highly subjective, but I think it would be nice if the main landing page would be entirely visible without scrolling on a 1080p display, in a maximized window, including any title/status/tool/task/panel bars, etc.

I think, for this, it would have to be just a little bit shorter, like ~900px tall, instead of the current ~960.
Tweaking some margins and paddings and spacings and sizes here and there should probably get us there easily.
I am not a designer though.

**Comment by danielhjacobs** [comment]
This is subjective, as you said. At work, my display is 1920x1200 and the Ruffle homepage is the perfect height for that size (see screenshot), but I acknowledge my monitor is larger than what most users have:
![Screenshot from 2024-03-05 16-15-55](https://github.com/ruffle-rs/ruffle-rs.github.io/assets/29206584/0181ba5d-7734-45ac-96df-e890658f96d2)
I'm also not a designer or I'd play around with this a bit.

**Comment by danielhjacobs** [comment]
https://github.com/ruffle-rs/ruffle-rs.github.io/blob/170f45aaa462b1b2bb16528e2e8cb86f4fb5a047/src/components/footer.module.css#L2

https://github.com/ruffle-rs/ruffle-rs.github.io/blob/170f45aaa462b1b2bb16528e2e8cb86f4fb5a047/src/components/header.module.css#L3

170 extra, possibly unnecessary, pixels of margins.

**Comment by danielhjacobs** [comment]
The page is also taller now that the links take up more lines.

**Comment by danielhjacobs** [comment]
It's a bit hard to say how tall the content actually is now. On an OS without any relevant links. the only buttons shown are "Website Package" and "Other Downloads", taking up just one line on a wide screen. On most OS's and browsers, the links instead take up 2-3 lines on a wide screen (3 lines as in the screenshot above, and 2 lines on most Windows and Mac computers or on an unsupported browser on Linux).

We can edit any of these three files, but screen sizes and window borders also vary a lot.

https://github.com/ruffle-rs/ruffle-rs.github.io/blob/170f45aaa462b1b2bb16528e2e8cb86f4fb5a047/src/components/footer.module.css#L2
https://github.com/ruffle-rs/ruffle-rs.github.io/blob/170f45aaa462b1b2bb16528e2e8cb86f4fb5a047/src/components/header.module.css#L3
https://github.com/ruffle-rs/ruffle-rs.github.io/blob/170f45aaa462b1b2bb16528e2e8cb86f4fb5a047/src/app/index.module.css#L30-L33

And tbh the biggest issue may be once we support i18n, the translations could end up making the page taller or shorter depending on the chosen language, and we can't monitor the size for every language.
