### ISSUE TITLE
"demo" isn't centered on the page

### ISSUE THREAD

**Issue by micpap25** [ruffle-rs/ruffle-rs.github.io#25]
In the main page, the "demo" option is not centered in the page. This is very noticeable because a there's a downward-pointing arrow right below it that is centered.

"demo" seems to not be centered because the distance between "read more", "demo", and "discord" was kept consistent instead. "read more" and "discord" are at consistent distances from the edges of the screen, so they shouldn't be moved.

 In my opinion the page would look nicer if "demo" was perfectly centered on the page rather than between the other two items on its line.

**Comment by Poopooracoocoo** [comment]
Yeah it does look a bit weird 
![image](https://user-images.githubusercontent.com/51363864/108336566-4792e680-7228-11eb-94d1-88b4b9657833.png)

**Comment by danielhjacobs** [comment]
I tried to make a PR for this, but it affected more than just "demo", so I closed it. Does anyone have more knowledge of CSS than I do to do this. I thought of a solution, but it's a bit hacky:

Changing <li><a href="https://ruffle.rs/demo/">Demo</a></li> to <li style="visibility:hidden;">Demo</li><li style="position: absolute;"><a href="https://ruffle.rs/demo/">Demo</a></li>
