### ISSUE TITLE
Please add the "perfect pitch" game

### ISSUE THREAD

**Issue by patrakov** [ruffle-rs/ruffle-rs.github.io#61]
There is a game, http://www.detrave.net/nblume/perfect-pitch/perfect-pitch.swf , that works perfectly when uploaded to https://ruffle.rs/demo/ as a local SWF. It may be a good idea to include it in the pre-set menu of demos and games ("Sample SWF") on the right hand side of the header.

**Comment by torokati44** [comment]
Thanks for the suggestion, and glad to hear it works well!
But for including it on the demo page, I think we would need the permission of the author, who in this case appears to be Nathan Blume.

**Comment by Herschel** [comment]
Thanks for the suggestion! But we indeed need permission from the author (many of the current demo SWFs are from Flash developers I know).
