### ISSUE TITLE
https://www.ruffle.rs throws a security warning

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle-rs.github.io#72]
https://www.ruffle.rs does not redirect to https://ruffle.rs.

It seems like the www version is missing an SSL certificate. The DNS entries are present and look correct, so I suppose this is just something with the [CNAME file](https://github.com/ruffle-rs/ruffle-rs.github.io/blob/bfa9f125ab312f364a6732a030be0bcadaf3481a/CNAME) on Github?

**Comment by danielhjacobs** [comment]
I think this requires a change to a repository setting. See https://github.blog/changelog/2021-04-08-github-pages-can-now-automatically-secure-the-www-variant-of-your-custom-domain/. If one of the maintainers of this repository can see if they can get this working, that would be cool.

Support for this was seemingly only added in April of this year, so it's no wonder this repository wasn't setup for it before.

**Comment by danielhjacobs** [comment]
I think @Herschel may need to fix this.

**Comment by Herschel** [comment]
Should be good now, thank you!
