### ISSUE TITLE
Add commit history bar graph

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle-rs.github.io#89]
GitHub has a nice bar graph showing the Ruffle repo's commit history: https://github.com/ruffle-rs/ruffle/graphs/commit-activity
![image](https://user-images.githubusercontent.com/71368227/169741128-fd310c4a-801b-4198-8cf4-7d0f6b8aa149.png)
In my opinion, this bar graph more accurately reflects the project progress and activity than the AVM1 and AVM2 progress bars. It shows that things are consistently being accomplished every week as code is committed.
I'd like to see a version of this bar graph along the bottom of the "Compatibility" section of the Ruffle website. Hopefully it can be nicely styled, similarly to the progress bars (but the bars would be vertical, not horizontal).
The data can be requested straight from GitHub's API using this URL: https://api.github.com/repos/ruffle-rs/ruffle/stats/commit_activity
In that data, the "week" value is a Unix epoch giving the start date of the week, and "total" is the number of commits during that week.

**Comment by danielhjacobs** [comment]
https://jsfiddle.net/st7bgjcd/. Going to bed now. Someone else can add this, as I don't know when I'll get to it.

**Comment by relrelb** [comment]
Added in #90.
