### ISSUE TITLE
AS2 getUrl() not passing scope variables via POST/HTTP

### ISSUE THREAD

**Issue by Underdog-01** [ruffle-rs/ruffle-rs.github.io#93]
In AS2 getUrl() will pass variables within the current function (scope) as POST/HTTP variables.
It would normally work directly off a button  such as .on(release) or for events such as .onPress() or .onRelease().
With the current version of Ruffle this seems to only work directly off a button using ie. .on(release) but fails to pass the POST/HTTP variables when used in an event handler.
This AS function getUrl() is a bit unique because it doesn't require passing the variables directly into the function arguments as an object.  It automatically gathers the object contents from the variables defined in the current function/scope.  

I've attached 2 examples in a zip.. eastereggslots works properly because it uses .on(release) directly off the button like an onload would do in a HTML tag to invoke an event. 
However if it's being used in an event handler such as .onPress() or .onRelease() it does not gather the local scope variables as object contents to pass them as POST/HTTP variables. The example with the failure is in the bopeep swf file.

bopeep.swf -> scripts -> frame10 -> approx. line 583 -> gameOverPost.btnSubmit.onPress() 
- fails to pass local scope defined variables via POST/HTTP using getUrl()

eastereggslots.swf -> scripts -> DEFINEBUTTON2(105) -> .on(release)
- successfully passes local scope defined variables via POST/HTTP using getUrl()  

file: [example-swf-files.zip](https://github.com/ruffle-rs/ruffle-rs.github.io/files/9229205/example-swf-files.zip)

**Comment by Underdog-01** [comment]
I forgot to add that this is being tested using the self hosted method which is how Ruffle is used in the SMF Arcade project/mod.

**Comment by n0samu** [comment]
Can you close this issue and add it to the main ruffle repo instead? https://github.com/ruffle-rs/ruffle/issues

**Comment by Underdog-01** [comment]
Done.
